### ISSUE TITLE
not correct url send

### ISSUE THREAD

**Issue by AlexanderAndria** [alexeevdv/yii2-sms#1]
Hi! Thank you for your work. Could you fix it in the file https://github.com/alexeevdv/yii2-sms/blob/master/src/provider/SmscRuProvider.php string 57
`$response = $this->apiCall('send', [`
'send' replace with **send.php**

**Comment by alexeevdv** [comment]
Hey. Thanks for pointing it out. Fixed in https://github.com/alexeevdv/yii2-sms/releases/tag/1.0.1
